# Developing Data Products
## Final course project

Author: Azmi Mohamed Ridwan

This repository is created to complete the Coursera module project requirements. It has 2 main components.

### A. Shiny App
Consisting of 2 files, ui.R and server.R, this is web application that will display
the results of a linear regression model on the mtcars dataset. Both files contain
comments detailing the application code.

**To run**
There are 3 main options:
1. You can access the application which is already running on the Shiny server (here)[http://azmimr.shinyapps.io/project-app/].
2. You can upload these files yourself onto your own shiny server.
3. If you have R Studio, you can open the file and click on the 'Run' command located 
on the top right portion of the window. Please do a search online if you need more assistance.

### B. Presentation
The accompanying presentation has been published on github. You can view the presentation 
(here)[http://azmimr.github.io/data_products_presentation/index.html].
The presentation will give a brief description of the application.